spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서는 `update` 사용
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅s
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE # 바인딩 값 로그
server:
  port: 8080 # 개발 서버 포트