mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: VARCHAR
    default-fetch-size: 500

spring:
  profiles:
    active: dev
    include: storage,thymeleaf, toss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 10MB

jwt:
  key: your-very-secret-jwt-key-which-should-be-long-enough123213sadasccxvxcvsad