spring:
  datasource:
    url: jdbc:mysql://mysql:3306/community
    username: dev
    password: 1111 # 운영 환경 비밀번호
  jpa:
    hibernate:
      ddl-auto: validate # 운영 환경에서는 스키마 변경 방지
logging:
  level:
    root: debug # 로그 레벨을 최소화
server:
  port: 8080 # 운영 서버 포트